// Generated by gencpp from file chat_messages/Text_message.msg
// DO NOT EDIT!


#ifndef CHAT_MESSAGES_MESSAGE_TEXT_MESSAGE_H
#define CHAT_MESSAGES_MESSAGE_TEXT_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace chat_messages
{
template <class ContainerAllocator>
struct Text_message_
{
  typedef Text_message_<ContainerAllocator> Type;

  Text_message_()
    : header()
    , sender()
    , text()  {
    }
  Text_message_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sender(_alloc)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::chat_messages::Text_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chat_messages::Text_message_<ContainerAllocator> const> ConstPtr;

}; // struct Text_message_

typedef ::chat_messages::Text_message_<std::allocator<void> > Text_message;

typedef boost::shared_ptr< ::chat_messages::Text_message > Text_messagePtr;
typedef boost::shared_ptr< ::chat_messages::Text_message const> Text_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chat_messages::Text_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chat_messages::Text_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chat_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'chat_messages': ['/home/mark/Project/TestingROS_Gui/src/chat_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chat_messages::Text_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chat_messages::Text_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chat_messages::Text_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chat_messages::Text_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chat_messages::Text_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chat_messages::Text_message_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chat_messages::Text_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ea06a482c2a35eda1e76e5a2ef3e7b7";
  }

  static const char* value(const ::chat_messages::Text_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ea06a482c2a35edULL;
  static const uint64_t static_value2 = 0xa1e76e5a2ef3e7b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::chat_messages::Text_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chat_messages/Text_message";
  }

  static const char* value(const ::chat_messages::Text_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chat_messages::Text_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string sender\n\
string text\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::chat_messages::Text_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chat_messages::Text_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sender);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Text_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chat_messages::Text_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chat_messages::Text_message_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHAT_MESSAGES_MESSAGE_TEXT_MESSAGE_H
